# Generated by Django 4.2.2 on 2023-09-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content_unlocked',
            field=models.JSONField(default=dict),
        ),
    ]
