import base64
from google import genai
from google.genai import types
import logging
from django.core.files.base import ContentFile
from observation.models import Species

# Initialize a logger for this module
logger = logging.getLogger(__name__)

# Global client for google.genai, initialized when the module is loaded.
# Ensure API key is configured (e.g., GOOGLE_API_KEY environment variable).
client = None

def generate_text(contents, model_name='gemini-2.0-flash'):
    global client
    if client is None:
        client = genai.Client()
    response = client.models.generate_content(model=model_name, contents=contents, config=types.GenerateContentConfig(response_mime_type="application/json"))
    return response.text

def generate_illustration(species: Species) -> bool:
    try:
        common_name = species.commonNames[0] if species.commonNames else species.scientificNameWithoutAuthor
        scientific_name = species.scientificNameWithoutAuthor
        prompt_text = f"quick rough watercolor and graphite sketch of a {common_name} ({scientific_name}), on a 19th century yellowish page"

        logger.info(f"Generating image for {scientific_name} with prompt: '{prompt_text}' using model imagen-4.0-generate-preview-06-06 via google.genai SDK")

        global client
        if client is None:
            client = genai.Client()
        
        image_response = client.models.generate_images(
            model="imagen-3.0-generate-002", # Hardcoded model name
            prompt=prompt_text
        )

        logger.info(f"Image generation API call completed for {scientific_name} using google.genai.")

        if image_response.generated_images:
            generated_image_object = image_response.generated_images[0].image

            # The API is returning a base64 encoded string in the `image_bytes` attribute.
            # This is a bit of a misnomer for the attribute name, but we handle it.
            # Let's check if the data exists before trying to decode.
            if not hasattr(generated_image_object, 'image_bytes') or not generated_image_object.image_bytes:
                logger.error(f"API response for {scientific_name} did not contain image data.")
                return False

            base64_encoded_string = generated_image_object.image_bytes

            # Decode the Base64 string into raw binary data
            try:
                image_bytes = base64.b64decode(base64_encoded_string)
            except (base64.binascii.Error, TypeError) as e:
                logger.error(f"Failed to decode base64 string for {scientific_name}: {e}")
                return False

            if not image_bytes:
                logger.error(f"Image bytes are empty after decoding for {scientific_name}.")
                return False

            file_name = f"{scientific_name.replace(' ', '_')}_illustration.png"

            # Save the decoded binary data
            species.illustration.save(file_name, ContentFile(image_bytes), save=False)
            species.save()

            logger.info(f"Successfully generated and saved illustration for {scientific_name} as {file_name}.")
            return True
        else:
            logger.warning(f"No images were generated by the API for {scientific_name}.")
            return False

    except Exception as e:
        logger.error(f"An error occurred in generate_illustration for {scientific_name} (using google.genai): {e}", exc_info=True)
        return False
