# Generated by Django 4.2.2 on 2023-06-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0004_alter_observation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='image',
            field=models.ImageField(upload_to='media/observation_image'),
        ),
    ]
