# Generated by Django 4.2.2 on 2023-06-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0005_alter_observation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='commonNames',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='species',
            name='genus',
            field=models.CharField(default='genus', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='scientificName',
            field=models.CharField(default='scientific name', max_length=255),
            preserve_default=False,
        ),
    ]
