# Generated by Django 4.2.2 on 2023-06-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0006_species_commonnames_species_genus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='family',
            field=models.CharField(default='family', max_length=255),
            preserve_default=False,
        ),
    ]
