# Generated by Django 4.2.2 on 2023-07-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation", "0007_species_family"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="date",
            field=models.DateField(),
        ),
    ]
