# Generated by Django 4.2.2 on 2023-07-11 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observation", "0008_alter_observation_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="species",
            options={"verbose_name_plural": "Species"},
        ),
    ]
