# Generated by Django 4.2.2 on 2023-07-20 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0010_alter_observation_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='date',
        ),
        migrations.AddField(
            model_name='observation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
