# Generated by Django 4.2.2 on 2023-08-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0012_alter_observation_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='identification_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
