# Generated by Django 4.2.2 on 2023-09-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0013_observation_identification_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='descriptions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='species',
            name='illustration',
            field=models.ImageField(blank=True, upload_to='media/illustration'),
        ),
        migrations.AddField(
            model_name='species',
            name='illustration_transparent',
            field=models.ImageField(blank=True, upload_to='media/illustration_transparent'),
        ),
        migrations.AddField(
            model_name='species',
            name='wikipedia_image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
