# Generated by Django 4.2.2 on 2023-09-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0015_alter_observation_image_alter_species_illustration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='name',
            new_name='scientificNameWithoutAuthor',
        ),
    ]
