# Generated by Django 4.2.2 on 2023-09-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0016_rename_name_species_scientificnamewithoutauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='commonNames',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='species',
            name='descriptions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
