# Generated by Django 4.2.2 on 2023-09-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0017_alter_species_commonnames_alter_species_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='occurences_cdf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='identification_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='location',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientificNameWithoutAuthor',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
