# Generated by Django 4.2.2 on 2023-09-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0018_species_occurences_cdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='scientificName',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientificNameWithoutAuthor',
            field=models.CharField(max_length=255),
        ),
    ]
