# Generated by Django 4.2.2 on 2023-09-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation", "0020_observation_xp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="species",
            name="scientificName",
        ),
        migrations.RemoveField(
            model_name="species",
            name="wikipedia_image_url",
        ),
        migrations.AddField(
            model_name="species",
            name="gbif_id",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="species",
            name="illustration_reference",
            field=models.ImageField(
                blank=True, upload_to="species/illustration_reference"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="illustration_reference_transparent",
            field=models.ImageField(
                blank=True, upload_to="species/illustration_reference_transparent"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="number_of_occurrences",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="powo_id",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="species",
            name="rarity_gpt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="reference_image_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="species",
            name="scientificNameAuthorship",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="species",
            name="wikipedia_word_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="scientificNameWithoutAuthor",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
