# Generated by Django 4.2.2 on 2023-09-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation", "0021_remove_species_scientificname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="scientificNameWithoutAuthor",
            field=models.CharField(max_length=255),
        ),
    ]
