# Generated by Django 4.2.2 on 2023-09-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation", "0022_alter_species_scientificnamewithoutauthor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="scientificNameWithoutAuthor",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
