# Generated by Django 4.2.5 on 2023-09-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0024_alter_observation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
