# Generated by Django 4.2.6 on 2023-10-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation", "0025_alter_observation_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="organ",
            field=models.CharField(default="flower", max_length=10),
            preserve_default=False,
        ),
    ]
