# Generated by Django 4.2.6 on 2024-01-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation", "0027_alter_observation_organ"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="type",
            field=models.CharField(
                choices=[("plant", "plant"), ("bird", "bird")],
                default="plant",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="species",
            name="type",
            field=models.CharField(
                choices=[("plant", "plant"), ("bird", "bird")],
                default="plant",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="observation",
            name="organ",
            field=models.CharField(
                choices=[
                    ("leaf", "leaf"),
                    ("flower", "flower"),
                    ("fruit", "fruit"),
                    ("bark", "bark"),
                    ("whole", "whole"),
                ],
                max_length=10,
            ),
        ),
    ]
