# Generated by Django 4.2.6 on 2024-01-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation", "0028_observation_type_species_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="avibase_id",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="species",
            name="protonyms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="species",
            name="rarity_status",
            field=models.CharField(default="", max_length=31),
        ),
        migrations.AlterField(
            model_name="observation",
            name="organ",
            field=models.CharField(
                choices=[
                    ("whole", "whole"),
                    ("leaf", "leaf"),
                    ("flower", "flower"),
                    ("fruit", "fruit"),
                    ("bark", "bark"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="gbif_id",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="species",
            name="powo_id",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
