# Generated by Django 4.2.6 on 2024-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation", "0029_species_avibase_id_species_protonyms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="rarity_status",
            field=models.CharField(blank=True, default="", max_length=31),
        ),
    ]
