# Generated by Django 5.2.3 on 2025-06-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0030_alter_species_rarity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='audio_description',
            field=models.FileField(blank=True, null=True, upload_to='species/audio_description'),
        ),
    ]
