# Generated by Django 6.0.1 on 2026-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observation", "0031_species_audio_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="body_length_cm",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
