from collections import defaultdict
from observation.models import Observation
from django.db.models import Q

class BadgeLogic:
    def __init__(self, name, description, levels, icon=None):
        self.name = name
        self.description = description
        self.icon = icon
        self.levels = levels

    def check_user_progress(self, user):
        progress = defaultdict(lambda: {"unlocked": False, "progress": 0})
        for level_name, threshold in self.levels.items():
            observed_count = self.calculate_progress(user)
            progress[level_name]["unlocked"] = observed_count >= threshold
            progress[level_name]["progress"] = observed_count
            progress[level_name]["threshold"] = threshold
            progress[level_name]["percentage"] = observed_count / threshold if threshold > 0 else 1
        return progress

    def calculate_progress(self, user):
        raise NotImplementedError("Subclasses must implement this method")


class SpeciesBadgeLogic(BadgeLogic):
    def __init__(self, name, description, levels, species_list, common_species_list=None, icon=None):
        super().__init__(name, description, levels, icon)
        self.species_list = species_list
        self.common_species_list = common_species_list if common_species_list else species_list

    def calculate_progress(self, user):
        # We look for the species name in both scientificNameWithoutAuthor and protonyms
        observed_species = Observation.objects.filter(
            Q(user=user, species__scientificNameWithoutAuthor__in=self.species_list) |
            Q(user=user, species__protonyms__overlap=self.species_list)
        )
        observed_species = set(obs.species.scientificNameWithoutAuthor for obs in observed_species.all())
        return len(observed_species)


class TotalObservationsBadgeLogic(BadgeLogic):
    def calculate_progress(self, user):
        return Observation.objects.filter(user=user).count()

# Badge registry (no need to create the badge instance here anymore)
BADGE_LOGICS = {
    "Corvid Connoisseur": SpeciesBadgeLogic(
        "Corvid Connoisseur", "Observe different corvid species.",
        levels={"Bronze": 3, "Silver": 5, "Gold": 8},
        species_list=["Corvus corax", "Corvus corone", "Corvus cornix", "Pica pica", "Nucifraga caryocatactes",
                     "Pyrrhocorax pyrrhocorax", "Pyrrhocorax graculus", "Coloeus monedula", "Corvus frugilegus",
                     "Corvus ruficollis", "Corvus rhipidurus", "Garrulus glandarius"],
        common_species_list=["Corvus corax", "Corvus corone", "Corvus cornix", "Pica pica", "Coloeus monedula", 
                             "Pyrrhocorax pyrrhocorax", "Pyrrhocorax graculus", "Corvus frugilegus", "Garrulus glandarius",
                             "Nucifraga caryocatactes"]
    ),
    "Owl Observer": SpeciesBadgeLogic(
        "Owl Observer", "Observe different owl species.",
        levels={"Bronze": 2, "Silver": 4, "Gold": 6},
        species_list=["Tyto alba", "Bubo bubo", "Otus scops", "Bubo scandiacus", "Surnia ulula", "Glaucidium passerinum",
                     "Athene noctua", "Strix aluco", "Strix mauritanica", "Strix uralensis", "Strix nebulosa",
                     "Asio otus", "Asio flammeus", "Asio capensis", "Aegolius funereus"],
        common_species_list=["Tyto alba", "Bubo bubo", "Otus scops", "Strix aluco", "Asio otus", "Asio flammeus"]
    ),
    "Waterfowl Whisperer": SpeciesBadgeLogic(
        "Waterfowl Whisperer", "Observe different waterfowl species.",
        levels={"Bronze": 5, "Silver": 10, "Gold": 15},
        species_list=["Dendrocygna viduata", "Dendrocygna bicolor", "Anser indicus", "Anser caerulescens",
                     "Anser rossii", "Anser anser", "Anser albifrons", "Anser erythropus", "Anser fabalis",
                     "Anser serrirostris", "Anser brachyrhynchus", "Branta bernicla", "Branta leucopsis",
                     "Branta hutchinsii", "Branta canadensis", "Branta ruficollis", "Cygnus olor", "Cygnus columbianus",
                     "Cygnus cygnus", "Alopochen aegyptiaca", "Tadorna ferruginea", "Tadorna tadorna", "Aix sponsa",
                     "Aix galericulata", "Sibirionetta formosa", "Spatula querquedula", "Spatula discors",
                     "Spatula clypeata", "Mareca strepera", "Mareca falcata", "Mareca penelope", "Mareca americana",
                     "Anas zonorhyncha", "Anas platyrhynchos", "Anas rubripes", "Anas acuta", "Anas crecca",
                     "Marmaronetta angustirostris", "Netta rufina", "Aythya valisineria", "Aythya americana",
                     "Aythya ferina", "Aythya collaris", "Aythya nyroca", "Aythya fuligula", "Aythya marila",
                     "Aythya affinis", "Polysticta stelleri", "Somateria fischeri", "Somateria spectabilis",
                     "Somateria mollissima", "Histrionicus histrionicus", "Melanitta perspicillata", "Melanitta fusca",
                     "Melanitta deglandi", "Melanitta stejnegeri", "Melanitta nigra", "Melanitta americana",
                     "Clangula hyemalis", "Bucephala albeola", "Bucephala clangula", "Bucephala islandica",
                     "Mergellus albellus", "Lophodytes cucullatus", "Mergus merganser", "Mergus serrator",
                     "Oxyura jamaicensis", "Oxyura leucocephala"],
        common_species_list=["Anser anser", "Anser albifrons", "Branta bernicla", "Branta leucopsis", 
                             "Branta canadensis", "Cygnus olor", "Cygnus columbianus", "Cygnus cygnus",
                             "Alopochen aegyptiaca", "Tadorna tadorna", "Spatula clypeata", "Mareca strepera", 
                             "Mareca penelope", "Anas platyrhynchos", "Anas acuta", "Anas crecca", 
                             "Aythya ferina", "Aythya fuligula", "Aythya marila", "Somateria mollissima",
                             "Clangula hyemalis", "Bucephala clangula", "Mergus merganser", "Mergus serrator"]
    ),
    "Wading Wonderer": SpeciesBadgeLogic(
        "Wading Wonderer", "Observe different wading bird species.",
        levels={"Bronze": 3, "Silver": 6, "Gold": 10},
        species_list=["Botaurus stellaris", "Botaurus lentiginosus", "Ixobrychus exilis", "Ixobrychus eurhythmus",
                     "Ixobrychus sturmii", "Ixobrychus minutus", "Nyctanassa violacea", "Nycticorax nycticorax",
                     "Egretta caerulea", "Egretta tricolor", "Egretta ardesiaca", "Egretta thula", "Egretta garzetta",
                     "Egretta gularis", "Butorides striata", "Butorides virescens", "Ardeola ralloides", 
                     "Ardeola grayii", "Ardeola bacchus", "Bubulcus ibis", "Ardea alba", "Ardea brachyrhyncha", 
                     "Ardea intermedia", "Ardea cinerea", "Ardea herodias", "Ardea purpurea", "Ardea melanocephala",
                     "Plegadis falcinellus", "Threskiornis aethiopicus", "Geronticus eremita", "Platalea leucorodia",
                     "Platalea alba", "Anthropoides virgo", "Leucogeranus leucogeranus", "Antigone canadensis",
                     "Grus grus", "Burhinus oedicnemus", "Pluvianus aegyptius", "Himantopus himantopus",
                     "Recurvirostra avosetta", "Haematopus ostralegus", "Haematopus palliatus", "Haematopus meadewaldoi",
                     "Pluvialis squatarola", "Pluvialis apricaria", "Pluvialis dominica", "Pluvialis fulva",
                     "Eudromias morinellus", "Charadrius vociferus", "Charadrius hiaticula", "Charadrius semipalmatus",
                     "Charadrius dubius", "Vanellus vanellus", "Vanellus spinosus", "Vanellus cinereus", 
                     "Vanellus gregarius", "Vanellus leucurus", "Anarhynchus asiaticus", "Anarhynchus veredus",
                     "Anarhynchus mongolus", "Anarhynchus atrifrons", "Anarhynchus leschenaultii", 
                     "Anarhynchus pecuarius", "Anarhynchus nivosus", "Anarhynchus alexandrinus", 
                     "Bartramia longicauda", "Tringa ochropus", "Tringa solitaria", "Tringa brevipes", "Tringa stagnatilis", 
                     "Tringa glareola", "Tringa totanus", "Tringa flavipes", "Tringa semipalmata", "Tringa erythropus",
                     "Tringa nebularia", "Tringa melanoleuca"],
        common_species_list=["Botaurus stellaris", "Nycticorax nycticorax", "Egretta garzetta", "Bubulcus ibis", 
                             "Ardea alba", "Ardea cinerea", "Ardea purpurea", "Plegadis falcinellus", "Platalea leucorodia",
                             "Grus grus", "Burhinus oedicnemus", "Himantopus himantopus", "Recurvirostra avosetta", 
                             "Haematopus ostralegus", "Pluvialis apricaria", "Eudromias morinellus", "Charadrius hiaticula",
                             "Charadrius dubius", "Vanellus vanellus", "Tringa ochropus", "Tringa glareola", 
                             "Tringa totanus", "Tringa erythropus", "Tringa nebularia"]
    ),
    "Backyard Birder": SpeciesBadgeLogic(
        "Backyard Birder", "Observe different birds commonly found in gardens.",
        levels={"Bronze": 5, "Silver": 10, "Gold": 15},
        species_list=["Columba livia", "Streptopelia turtur", "Streptopelia decaocto", "Coturnix coturnix",
                     "Alectoris rufa", "Phasianus colchicus", "Perdix perdix", "Gallinula chloropus",
                     "Fulica atra", "Pica pica",
                     "Corvus corone", "Corvus cornix", "Corvus monedula", "Corvus frugilegus", 
                     "Passer domesticus", "Passer montanus", "Petronia petronia", "Motacilla alba", 
                     "Motacilla flava", "Alauda arvensis", "Galerida cristata", "Erithacus rubecula", 
                     "Turdus merula", "Turdus philomelos", "Turdus iliacus", "Turdus viscivorus", 
                     "Fringilla coelebs", "Carduelis carduelis", "Chloris chloris", "Linaria cannabina", 
                     "Emberiza citrinella", "Emberiza calandra", "Emberiza cia", "Emberiza schoeniclus", 
                     "Sylvia atricapilla", "Sylvia borin", "Curruca nisoria", "Curruca curruca", "Curruca melanocephala",
                     "Regulus regulus", "Sitta europaea", "Certhia familiaris", "Troglodytes troglodytes",
                     "Cinclus cinclus", "Sturnus vulgaris", "Pyrrhula pyrrhula", "Spinus spinus", 
                     "Acanthis flammea", "Loxia curvirostra", "Falco tinnunculus", "Otus scops", 
                     "Strix aluco", "Asio otus", "Asio flammeus", "Upupa epops", "Alcedo atthis",
                     "Merops apiaster", "Coracias garrulus", "Jynx torquilla", "Picoides tridactylus", 
                     "Dendrocoptes medius", "Dendrocopos major", "Dryobates minor", "Picus viridis", 
                     "Dryocopus martius", "Periparus ater", "Lophophanes cristatus", "Poecile palustris", 
                     "Poecile montanus", "Cyanistes caeruleus", "Parus major", "Remiz pendulinus", 
                     "Alaudala rufescens", "Lullula arborea", "Galerida cristata", "Panurus biarmicus", 
                     "Acrocephalus schoenobaenus", "Locustella naevia", "Riparia riparia", "Hirundo rustica", 
                     "Delichon urbicum", "Phylloscopus sibilatrix", "Phylloscopus bonelli", 
                     "Phylloscopus trochilus", "Phylloscopus collybita", "Cettia cetti", "Aegithalos caudatus", 
                     "Sylvia atricapilla", "Sylvia borin", "Curruca nisoria", "Curruca curruca", 
                     "Curruca melanocephala", "Regulus regulus", "Sitta europaea", "Certhia familiaris", 
                     "Troglodytes troglodytes", "Cinclus cinclus", "Sturnus vulgaris", "Pyrrhula pyrrhula", 
                     "Spinus spinus", "Acanthis flammea", "Loxia curvirostra"],
        common_species_list=["Columba livia", "Streptopelia decaocto", "Passer domesticus",
                             "Motacilla alba", "Alauda arvensis", "Erithacus rubecula", "Turdus merula",
                             "Turdus philomelos", "Fringilla coelebs", "Carduelis carduelis", 
                             "Chloris chloris", "Linaria cannabina", "Emberiza citrinella", 
                             "Sylvia atricapilla", "Sylvia borin", "Regulus regulus", "Sitta europaea", 
                             "Certhia familiaris", "Troglodytes troglodytes", "Sturnus vulgaris", 
                             "Pyrrhula pyrrhula", "Spinus spinus"]
    ),
    "Woodland Wanderer": SpeciesBadgeLogic(
        "Woodland Wanderer", "Observe different birds commonly found in woodlands.",
        levels={"Bronze": 5, "Silver": 10, "Gold": 15},
        species_list=["Tetrastes bonasia", "Lagopus lagopus", "Lagopus muta", "Tetrao urogallus", "Lyrurus tetrix",
                     "Columba palumbus", "Streptopelia turtur", "Streptopelia decaocto", "Cuculus canorus",
                     "Caprimulgus europaeus", "Apus apus", "Apus unicolor", "Apus pallidus", "Rallus aquaticus",
                     "Crex crex", "Porzana porzana", "Gallinula chloropus", "Fulica atra", "Ixobrychus minutus",
                     "Botaurus stellaris", "Nycticorax nycticorax", "Ardea purpurea",
                     "Ciconia nigra", "Pernis apivorus", "Buteo buteo", "Buteo lagopus", "Accipiter gentilis", "Accipiter nisus",
                     "Strix aluco", "Asio otus", "Asio flammeus", "Aegolius funereus", "Glaucidium passerinum", "Athene noctua",
                     "Upupa epops", "Jynx torquilla", "Picoides tridactylus", "Dendrocoptes medius", "Dendrocopos leucotos",
                     "Dendrocopos major", "Dendrocopos syriacus", "Dryobates minor", "Picus canus", "Picus viridis", "Picus sharpei",
                     "Dryocopus martius", "Garrulus glandarius", "Cyanopica cooki", "Pica pica", "Nucifraga caryocatactes",
                     "Perisoreus infaustus", "Periparus ater", "Lophophanes cristatus", "Poecile palustris", "Poecile montanus",
                     "Cyanistes caeruleus", "Parus major", "Remiz pendulinus", "Phylloscopus sibilatrix", "Phylloscopus bonelli",
                     "Phylloscopus orientalis", "Phylloscopus inornatus", "Phylloscopus humei", "Phylloscopus proregulus",
                     "Phylloscopus schwarzi", "Phylloscopus griseolus", "Phylloscopus fuscatus", "Phylloscopus neglectus",
                     "Phylloscopus trochilus", "Phylloscopus sindianus", "Phylloscopus canariensis", "Phylloscopus collybita",
                     "Phylloscopus ibericus", "Phylloscopus coronatus", "Phylloscopus nitidus", "Phylloscopus trochiloides",
                     "Phylloscopus plumbeitarsus", "Phylloscopus tenellipes", "Phylloscopus borealis",
                     "Phylloscopus examinandus", "Cettia cetti", "Aegithalos caudatus", "Sylvia atricapilla",
                     "Sylvia borin", "Curruca nisoria", "Curruca curruca", "Curruca hortensis", "Curruca crassirostris",
                     "Curruca deserti", "Curruca nana", "Curruca deserticola", "Curruca mystacea", "Curruca ruppeli",
                     "Curruca melanothorax", "Curruca melanocephala", "Curruca subalpina", "Curruca iberiae",
                     "Curruca cantillans", "Curruca communis", "Curruca conspicillata", "Curruca sarda", "Curruca undata",
                     "Curruca balearica", "Troglodytes troglodytes", "Regulus regulus", "Regulus ignicapilla",
                     "Regulus madeirensis", "Sitta europaea", "Sitta neumayer", "Certhia familiaris", "Certhia brachydactyla",
                     "Fringilla coelebs", "Fringilla montifringilla", "Pyrrhula pyrrhula", "Carduelis carduelis",
                     "Linaria cannabina", "Spinus spinus", "Emberiza citrinella", "Emberiza cia", "Emberiza calandra",
                     "Emberiza hortulana", "Emberiza schoeniclus"],
        common_species_list=["Columba palumbus", "Cuculus canorus", "Caprimulgus europaeus", "Apus apus", 
                             "Rallus aquaticus", "Crex crex", "Gallinula chloropus", "Fulica atra", "Ixobrychus minutus",
                             "Botaurus stellaris", "Nycticorax nycticorax", "Pernis apivorus", "Buteo buteo", 
                             "Accipiter gentilis", "Accipiter nisus", "Strix aluco", "Asio otus", "Asio flammeus", 
                             "Jynx torquilla", "Dendrocopos major", "Garrulus glandarius", "Pica pica", 
                             "Periparus ater", "Lophophanes cristatus", "Poecile palustris", "Poecile montanus",
                             "Cyanistes caeruleus", "Parus major", "Remiz pendulinus", "Phylloscopus sibilatrix",
                             "Phylloscopus collybita", "Phylloscopus trochilus", "Cettia cetti", "Aegithalos caudatus",
                             "Sylvia atricapilla", "Sylvia borin", "Curruca nisoria", "Curruca curruca", "Curruca melanocephala",
                             "Troglodytes troglodytes", "Regulus regulus", "Sitta europaea", "Certhia familiaris", 
                             "Fringilla coelebs", "Fringilla montifringilla", "Pyrrhula pyrrhula", "Carduelis carduelis",
                             "Linaria cannabina", "Spinus spinus", "Emberiza citrinella", "Emberiza cia", "Emberiza calandra",
                             "Emberiza hortulana", "Emberiza schoeniclus"] 
    ),
    "Coastal Connoisseur": SpeciesBadgeLogic(
        "Coastal Connoisseur", "Observe different birds commonly found on coastlines.",
        levels={"Bronze": 5, "Silver": 10, "Gold": 15},
        species_list=["Lagopus muta", "Branta bernicla", "Branta leucopsis", "Branta canadensis", "Tadorna tadorna",
                     "Haematopus ostralegus", "Haematopus palliatus", "Pluvialis squatarola", "Pluvialis apricaria",
                     "Charadrius hiaticula", "Charadrius dubius", "Vanellus vanellus", "Numenius phaeopus",
                     "Numenius arquata", "Limosa lapponica", "Limosa limosa", "Calidris canutus", "Calidris alpina",
                     "Calidris alba", "Calidris maritima", "Actitis hypoleucos", "Tringa totanus", "Tringa nebularia",
                     "Arenaria interpres", "Clangula hyemalis", "Bucephala clangula", "Bucephala islandica",
                     "Mergellus albellus", "Mergus merganser", "Mergus serrator", "Phalacrocorax carbo",
                     "Gulosus aristotelis", "Fratercula arctica", "Fratercula corniculata", "Cepphus grylle", "Alca torda",
                     "Alle alle", "Uria lomvia", "Uria aalge", "Synthliboramphus antiquus", "Rissa tridactyla",
                     "Pagophila eburnea", "Larus canus", "Larus argentatus", "Larus fuscus", "Larus marinus",
                     "Larus hyperboreus", "Larus michahellis", "Ichthyaetus melanocephalus", "Chroicocephalus ridibundus",
                     "Leucophaeus atricilla", "Sterna hirundo", "Sterna paradisaea", "Thalasseus sandvicensis",
                     "Rynchops niger", "Oceanites oceanicus", "Pelagodroma marina", "Hydrobates pelagicus",
                     "Oceanodroma leucorhoa", "Fulmarus glacialis", "Daption capense", "Calonectris diomedea",
                     "Ardenna gravis", "Puffinus puffinus", "Puffinus yelkouan", "Puffinus mauretanicus", "Pandion haliaetus",
                     "Haliaeetus albicilla", "Haliaeetus pelagicus"],
        common_species_list=["Branta bernicla", "Branta leucopsis", "Branta canadensis", "Tadorna tadorna",
                             "Haematopus ostralegus", "Pluvialis squatarola", "Charadrius hiaticula", "Charadrius dubius",
                             "Vanellus vanellus", "Numenius arquata", "Limosa lapponica", "Calidris canutus", 
                             "Calidris alpina", "Calidris alba", "Actitis hypoleucos", "Tringa totanus", "Tringa nebularia", 
                             "Arenaria interpres", "Clangula hyemalis", "Bucephala clangula", "Mergus merganser", 
                             "Phalacrocorax carbo", "Gulosus aristotelis", "Fratercula arctica", "Cepphus grylle", 
                             "Alca torda", "Uria lomvia", "Uria aalge", "Rissa tridactyla", "Larus canus", "Larus argentatus",
                             "Larus fuscus", "Larus marinus", "Sterna hirundo", "Sterna paradisaea", "Thalasseus sandvicensis",
                             "Fulmarus glacialis", "Calonectris diomedea", "Puffinus puffinus", "Pandion haliaetus",
                             "Haliaeetus albicilla"] 
    ),
    "Coastal Connoisseur": SpeciesBadgeLogic(
        "Coastal Connoisseur", "Observe different seabird species.",
        levels={"Bronze": 5, "Silver": 10, "Gold": 15},
        species_list=["Fratercula arctica", "Cepphus grylle", "Alca torda", "Uria lomvia", "Uria aalge",
                     "Rissa tridactyla", "Larus canus", "Larus argentatus", "Larus fuscus", "Larus marinus", 
                     "Sterna paradisaea", "Sterna hirundo", "Sterna sandvicensis", "Thalasseus maximus",
                     "Fulmarus glacialis", "Calonectris diomedea", "Calonectris edwardsii",  "Puffinus puffinus", 
                     "Puffinus yelkouan", "Puffinus mauretanicus", "Morus bassanus", "Phalacrocorax carbo", 
                     "Gulosus aristotelis", "Branta bernicla", "Branta leucopsis", "Tadorna tadorna", 
                     "Haematopus ostralegus", "Pluvialis squatarola", "Numenius arquata", "Limosa lapponica",
                     "Calidris canutus", "Calidris alpina", "Arenaria interpres"],
        common_species_list=["Fratercula arctica", "Cepphus grylle", "Alca torda", "Uria aalge",
                             "Rissa tridactyla", "Larus canus", "Larus argentatus", "Larus fuscus", "Larus marinus", 
                             "Sterna paradisaea", "Sterna hirundo", "Sterna sandvicensis", "Thalasseus maximus",
                             "Fulmarus glacialis", "Calonectris diomedea",  "Puffinus puffinus", 
                             "Morus bassanus", "Phalacrocorax carbo", "Gulosus aristotelis", "Branta bernicla", 
                             "Branta leucopsis", "Tadorna tadorna", "Haematopus ostralegus", "Pluvialis squatarola",
                             "Numenius arquata", "Limosa lapponica", "Calidris canutus", "Calidris alpina", 
                             "Arenaria interpres"]
    ),
    "Songbird Specialist": SpeciesBadgeLogic(
        "Songbird Specialist", "Observe different songbird species.",
        levels={"Bronze": 10, "Silver": 20, "Gold": 30},
        species_list=["Alaemon alaudipes", "Ramphocoris clotbey", "Ammomanes cinctura", "Ammomanes deserti",
                     "Eremophila alpestris", "Eremophila bilopha", "Calandrella brachydactyla", "Melanocorypha bimaculata",
                     "Melanocorypha calandra", "Melanocorypha yeltoniensis", "Chersophilus duponti", "Alaudala rufescens",
                     "Alaudala heinei", "Lullula arborea", "Alauda leucoptera", "Alauda arvensis", "Galerida theklae",
                     "Galerida cristata", "Panurus biarmicus", "Cisticola juncidis", "Arundinax aedon", "Iduna caligata",
                     "Iduna rama", "Iduna pallida", "Iduna opaca", "Hippolais languida", "Hippolais olivetorum",
                     "Hippolais polyglotta", "Hippolais icterina", "Acrocephalus paludicola", "Acrocephalus melanopogon",
                     "Acrocephalus schoenobaenus", "Acrocephalus agricola", "Acrocephalus dumetorum", "Acrocephalus palustris",
                     "Acrocephalus scirpaceus", "Acrocephalus arundinaceus", "Acrocephalus stentoreus", 
                     "Helopsaltes fasciolatus", "Helopsaltes certhiola", "Locustella lanceolata", "Locustella fluviatilis",
                     "Locustella luscinioides", "Locustella naevia", "Riparia paludicola", "Riparia riparia",
                     "Tachycineta bicolor", "Progne subis", "Stelgidopteryx serripennis", "Ptyonoprogne rupestris",
                     "Ptyonoprogne fuligula", "Hirundo rustica", "Delichon urbicum", "Delichon lagopodum", "Delichon dasypus",
                     "Cecropis daurica", "Petrochelidon pyrrhonota", "Pycnonotus barbatus", "Lanius collurio",
                     "Lanius phoenicuroides", "Lanius isabellinus", "Lanius cristatus", "Lanius schach", "Lanius borealis",
                     "Lanius meridionalis", "Lanius excubitor", "Lanius minor", "Lanius nubicus", "Lanius senator", 
                     "Prunella collaris", "Prunella montanella", "Prunella atrogularis", "Prunella modularis",
                     "Passer domesticus", "Passer italiae", "Passer hispaniolensis", "Passer moabiticus", "Passer iagoensis",
                     "Passer montanus", "Petronia petronia", "Carpospiza brachydactyla", "Montifringilla nivalis",
                     "Motacilla cinerea", "Motacilla flava", "Motacilla tschutschensis", "Motacilla citreola", "Motacilla alba",
                     "Anthus richardi", "Anthus rufulus", "Anthus similis", "Anthus godlewskii", "Anthus campestris",
                     "Anthus berthelotii", "Anthus pratensis", "Anthus trivialis", "Anthus hodgsoni", "Anthus gustavi",
                     "Anthus cervinus", "Anthus spinoletta", "Anthus petrosus", "Anthus rubescens", "Fringilla coelebs",
                     "Fringilla moreletti", "Fringilla maderensis", "Fringilla canariensis", "Fringilla spodiogenys",
                     "Fringilla teydea", "Fringilla polatzeki", "Fringilla montifringilla", "Coccothraustes vespertinus",
                     "Coccothraustes coccothraustes", "Carpodacus erythrinus", "Carpodacus roseus", "Pinicola enucleator",
                     "Pyrrhula murina", "Pyrrhula pyrrhula", "Bucanetes githagineus", "Bucanetes mongolicus",
                     "Haemorhous mexicanus", "Chloris chloris", "Linaria flavirostris", "Linaria cannabina", 
                     "Acanthis flammea", "Acanthis cabaret", "Acanthis hornemanni", "Loxia pytyopsittacus", "Loxia scotica", 
                     "Loxia curvirostra", "Loxia leucoptera", "Carduelis carduelis", "Carduelis citrinella", 
                     "Carduelis corsicana", "Serinus serinus", "Serinus canaria", "Serinus pusillus", "Serinus canicollis", 
                     "Spinus spinus", "Calcarius lapponicus", "Plectrophenax nivalis", "Emberiza melanocephala", 
                     "Emberiza bruniceps", "Emberiza calandra", "Emberiza fucata", "Emberiza cia", "Emberiza cioides", 
                     "Emberiza cirlus", "Emberiza citrinella", "Emberiza leucocephalos", "Emberiza buchanani", 
                     "Emberiza cineracea", "Emberiza hortulana", "Emberiza caesia", "Emberiza sahari", "Emberiza striolata", 
                     "Emberiza pallasi", "Emberiza schoeniclus", "Emberiza aureola", "Emberiza pusilla", "Emberiza rustica",
                     "Emberiza spodocephala", "Emberiza rutila", "Emberiza chrysophrys", "Zoothera aurea",
                     "Zoothera dauma", "Ixoreus naevius", "Catharus fuscescens", "Catharus minimus", "Catharus ustulatus",
                     "Catharus guttatus", "Hylocichla mustelina", "Geokichla sibirica", "Turdus viscivorus",
                     "Turdus philomelos", "Turdus iliacus", "Turdus merula", "Turdus migratorius", "Turdus falcklandii",
                     "Turdus obscurus", "Turdus pallidus", "Turdus pilaris", "Turdus torquatus", "Turdus atrogularis",
                     "Turdus ruficollis", "Turdus eunomus", "Turdus naumanni", "Muscicapa sibirica", "Muscicapa dauurica",
                     "Muscicapa striata", "Cercotrichas galactotes", "Erithacus rubecula", "Larvivora sibilans",
                     "Larvivora cyane", "Irania gutturalis", "Luscinia luscinia", "Luscinia megarhynchos",
                     "Luscinia svecica", "Calliope calliope", "Tarsiger cyanurus", "Ficedula mugimaki", "Ficedula albicilla",
                     "Ficedula parva", "Ficedula semitorquata", "Ficedula hypoleuca", "Ficedula speculigera",
                     "Ficedula albicollis", "Phoenicurus moussieri", "Phoenicurus phoenicurus", "Phoenicurus erythrogastrus",
                     "Phoenicurus ochruros", "Monticola saxatilis", "Monticola solitarius", "Saxicola rubetra",
                     "Saxicola dacotiae", "Saxicola rubicola", "Saxicola maurus", "Saxicola stejnegeri", "Saxicola torquatus",
                     "Saxicola caprata", "Oenanthe oenanthe", "Oenanthe seebohmi", "Oenanthe isabellina",
                     "Oenanthe deserti", "Oenanthe hispanica", "Oenanthe cypriaca", "Oenanthe melanoleuca",
                     "Oenanthe pleschanka", "Oenanthe moesta", "Oenanthe leucura", "Oenanthe leucopyga",
                     "Oenanthe finschii", "Oenanthe lugens", "Oenanthe xanthoprymna", "Bombycilla garrulus",
                     "Bombycilla cedrorum", "Contopus virens", "Empidonax flaviventris", "Empidonax virescens",
                     "Empidonax alnorum", "Empidonax minimus", "Sayornis phoebe", "Tyrannus verticalis", "Tyrannus tyrannus",
                     "Tyrannus savana", "Vireo griseus", "Vireo flavifrons", "Vireo philadelphicus", "Vireo olivaceus",
                     "Corthylio calendula", "Tichodroma muraria", "Sitta krueperi", "Sitta canadensis", "Sitta whiteheadi",
                     "Sitta neumayer", "Sitta europaea", "Certhia familiaris", "Certhia brachydactyla", "Troglodytes troglodytes",
                     "Cistothorus palustris", "Cinclus cinclus", "Sturnus vulgaris", "Sturnus unicolor", "Pastor roseus",
                     "Agropsar sturninus", "Acridotheres tristis", "Acridotheres cristatellus", "Dumetella carolinensis",
                     "Toxostoma rufum", "Mimus gilvus", "Mimus polyglottos", "Xanthocephalus xanthocephalus",
                     "Dolichonyx oryzivorus", "Icterus galbula", "Agelaius phoeniceus", "Molothrus ater", "Quiscalus quiscula",
                     "Quiscalus major", "Seiurus aurocapilla", "Parkesia motacilla", "Parkesia noveboracensis",
                     "Vermivora chrysoptera", "Vermivora cyanoptera", "Mniotilta varia", "Protonotaria citrea",
                     "Leiothlypis peregrina", "Oporornis agilis", "Geothlypis trichas", "Setophaga citrina",
                     "Setophaga ruticilla", "Setophaga tigrina", "Setophaga cerulea", "Setophaga americana",
                     "Setophaga magnolia", "Setophaga castanea", "Setophaga fusca", "Setophaga petechia",
                     "Setophaga pensylvanica", "Setophaga striata", "Setophaga caerulescens", "Setophaga palmarum",
                     "Setophaga pinus", "Setophaga coronata", "Setophaga dominica", "Setophaga discolor",
                     "Setophaga virens", "Cardellina canadensis", "Cardellina pusilla", "Piranga rubra",
                     "Piranga olivacea", "Pheucticus ludovicianus", "Passerina caerulea", "Passerina cyanea", "Spiza americana",
                     "Lonchura punctulata", "Lonchura malacca", "Lonchura atricapilla", "Estrilda melpoda", "Estrilda astrild",
                     "Amandava amandava", "Psittacula krameri", "Myiopsitta monachus"],
        common_species_list=["Alauda arvensis", "Panurus biarmicus", "Cisticola juncidis", "Acrocephalus schoenobaenus", 
                             "Locustella naevia", "Hirundo rustica", "Delichon urbicum", "Erithacus rubecula", "Turdus merula", 
                             "Turdus philomelos", "Turdus iliacus", "Turdus viscivorus", "Fringilla coelebs", 
                             "Carduelis carduelis", "Chloris chloris", "Linaria cannabina", "Emberiza citrinella", 
                             "Emberiza calandra", "Emberiza cia", "Emberiza schoeniclus"]
    ),
    "Raptor Ranger": SpeciesBadgeLogic(
        "Raptor Ranger", "Observe different raptor species.",
        levels={"Bronze": 4, "Silver": 8, "Gold": 12},
        species_list=["Pandion haliaetus", "Elanus caeruleus", "Gypaetus barbatus", "Neophron percnopterus",
                     "Pernis apivorus", "Pernis ptilorhynchus", "Elanoides forficatus", "Aegypius monachus",
                     "Torgos tracheliotos", "Necrosyrtes monachus", "Gyps africanus", "Gyps rueppelli", "Gyps fulvus",
                     "Circaetus gallicus", "Clanga pomarina", "Clanga clanga", "Hieraaetus pennatus", "Aquila nipalensis",
                     "Aquila adalberti", "Aquila heliaca", "Aquila chrysaetos", "Aquila fasciata", "Melierax metabates",
                     "Circus aeruginosus", "Circus cyaneus", "Circus hudsonius", "Circus macrourus", "Circus pygargus",
                     "Accipiter brevipes", "Accipiter nisus", "Accipiter gentilis", "Accipiter atricapillus", "Milvus milvus",
                     "Milvus migrans", "Haliaeetus pelagicus", "Haliaeetus leucoryphus", "Haliaeetus albicilla",
                     "Haliaeetus leucocephalus", "Buteo swainsoni", "Buteo lagopus", "Buteo buteo", "Buteo rufinus",
                     "Buteo hemilasius", "Falco naumanni", "Falco tinnunculus", "Falco sparverius", "Falco vespertinus",
                     "Falco amurensis", "Falco eleonorae", "Falco concolor", "Falco columbarius", "Falco subbuteo",
                     "Falco biarmicus", "Falco cherrug", "Falco rusticolus", "Falco peregrinus"],
        common_species_list=["Pandion haliaetus", "Pernis apivorus", "Buteo buteo", "Circus aeruginosus", "Circus cyaneus",
                             "Circus pygargus", "Accipiter nisus", "Accipiter gentilis", "Milvus milvus", "Milvus migrans", 
                             "Haliaeetus albicilla", "Falco tinnunculus", "Falco sparverius", "Falco peregrinus"] 
    )
}