"""Poster configurations including regional and species-group posters."""

# Poster types: "regional" uses common names, "species_group" uses scientific names
POSTERS = {
    # Regional Posters
    "western_us": {
        "name": "Western United States",
        "type": "regional",
        "icon": "🌄",
        "species": [
            "American Robin",
            "House Finch",
            "Anna's Hummingbird",
            "Black-capped Chickadee",
            "American Crow",
            "Northern Mockingbird",
            "Mourning Dove",
            "Red-tailed Hawk",
            "House Sparrow",
            "European Starling",
            "Steller's Jay",
            "Black Phoebe",
            "Yellow-rumped Warbler",
            "White-crowned Sparrow",
            "Dark-eyed Junco",
            "Lesser Goldfinch",
            "American Goldfinch",
            "Red-winged Blackbird",
            "Song Sparrow",
            "Downy Woodpecker",
            "Hairy Woodpecker",
            "Cooper's Hawk",
            "Turkey Vulture",
            "Great Blue Heron",
            "Mallard",
            "Canada Goose",
            "Bald Eagle",
            "Western Meadowlark",
            "Mountain Chickadee",
            "Rufous Hummingbird",
        ],
    },
    "uk": {
        "name": "United Kingdom",
        "type": "regional",
        "icon": "🇬🇧",
        "species": [
            "European Robin",
            "House Sparrow",
            "Blue Tit",
            "Great Tit",
            "Blackbird",
            "Chaffinch",
            "Woodpigeon",
            "Magpie",
            "Carrion Crow",
            "Goldfinch",
            "Long-tailed Tit",
            "Wren",
            "Dunnock",
            "Coal Tit",
            "Greenfinch",
            "Great Spotted Woodpecker",
            "Nuthatch",
            "Jay",
            "Collared Dove",
            "Starling",
            "Song Thrush",
            "Mistle Thrush",
            "Pheasant",
            "Red Kite",
            "Buzzard",
            "Kestrel",
            "Grey Heron",
            "Mallard",
            "Mute Swan",
            "Canada Goose",
        ],
    },
    "france": {
        "name": "France",
        "type": "regional",
        "icon": "🇫🇷",
        "species": [
            "European Robin",
            "House Sparrow",
            "Blue Tit",
            "Great Tit",
            "Blackbird",
            "Chaffinch",
            "Woodpigeon",
            "Magpie",
            "Carrion Crow",
            "Goldfinch",
            "Long-tailed Tit",
            "Wren",
            "Serin",
            "Greenfinch",
            "Great Spotted Woodpecker",
            "Nuthatch",
            "Jay",
            "Collared Dove",
            "Starling",
            "Song Thrush",
            "Hoopoe",
            "Bee-eater",
            "Red Kite",
            "Buzzard",
            "Kestrel",
            "Grey Heron",
            "Mallard",
            "Mute Swan",
            "Great Egret",
            "Black-headed Gull",
        ],
    },
    # Species Group Posters (from badges)
    "corvids": {
        "name": "Corvid Connoisseur",
        "type": "species_group",
        "icon": "🪶",
        "species": [
            "Corvus corax",
            "Corvus corone",
            "Corvus cornix",
            "Pica pica",
            "Nucifraga caryocatactes",
            "Pyrrhocorax pyrrhocorax",
            "Pyrrhocorax graculus",
            "Coloeus monedula",
            "Corvus frugilegus",
            "Garrulus glandarius",
        ],
    },
    "owls": {
        "name": "Owl Observer",
        "type": "species_group",
        "icon": "🦉",
        "species": [
            "Tyto alba",
            "Bubo bubo",
            "Otus scops",
            "Athene noctua",
            "Strix aluco",
            "Asio otus",
            "Asio flammeus",
        ],
    },
    "waterfowl": {
        "name": "Waterfowl Whisperer",
        "type": "species_group",
        "icon": "🦆",
        "species": [
            "Anser anser",
            "Branta bernicla",
            "Branta leucopsis",
            "Branta canadensis",
            "Cygnus olor",
            "Cygnus cygnus",
            "Tadorna tadorna",
            "Anas platyrhynchos",
            "Anas crecca",
            "Aythya ferina",
            "Aythya fuligula",
            "Bucephala clangula",
            "Mergus merganser",
        ],
    },
    "waders": {
        "name": "Wading Wonderer",
        "type": "species_group",
        "icon": "🦩",
        "species": [
            "Ardea cinerea",
            "Ardea alba",
            "Egretta garzetta",
            "Bubulcus ibis",
            "Nycticorax nycticorax",
            "Botaurus stellaris",
            "Grus grus",
            "Himantopus himantopus",
            "Recurvirostra avosetta",
            "Haematopus ostralegus",
            "Vanellus vanellus",
            "Pluvialis apricaria",
        ],
    },
    "raptors": {
        "name": "Raptor Ranger",
        "type": "species_group",
        "icon": "🦅",
        "species": [
            "Buteo buteo",
            "Milvus milvus",
            "Milvus migrans",
            "Accipiter nisus",
            "Accipiter gentilis",
            "Circus aeruginosus",
            "Circus cyaneus",
            "Pernis apivorus",
            "Haliaeetus albicilla",
            "Aquila chrysaetos",
            "Falco tinnunculus",
            "Falco peregrinus",
            "Pandion haliaetus",
        ],
    },
    "woodland": {
        "name": "Woodland Wanderer",
        "type": "species_group",
        "icon": "🌲",
        "species": [
            "Dendrocopos major",
            "Picus viridis",
            "Sitta europaea",
            "Certhia familiaris",
            "Garrulus glandarius",
            "Parus major",
            "Cyanistes caeruleus",
            "Poecile palustris",
            "Aegithalos caudatus",
            "Regulus regulus",
            "Phylloscopus collybita",
            "Sylvia atricapilla",
        ],
    },
    "coastal": {
        "name": "Coastal Connoisseur",
        "type": "species_group",
        "icon": "🌊",
        "species": [
            "Larus argentatus",
            "Larus fuscus",
            "Larus marinus",
            "Larus canus",
            "Rissa tridactyla",
            "Sterna hirundo",
            "Sterna paradisaea",
            "Fratercula arctica",
            "Alca torda",
            "Uria aalge",
            "Phalacrocorax carbo",
            "Morus bassanus",
        ],
    },
    "songbirds": {
        "name": "Songbird Specialist",
        "type": "species_group",
        "icon": "🎵",
        "species": [
            "Erithacus rubecula",
            "Turdus merula",
            "Turdus philomelos",
            "Luscinia megarhynchos",
            "Fringilla coelebs",
            "Carduelis carduelis",
            "Chloris chloris",
            "Emberiza citrinella",
            "Alauda arvensis",
            "Hirundo rustica",
            "Delichon urbicum",
            "Sturnus vulgaris",
        ],
    },
    "backyard": {
        "name": "Backyard Birder",
        "type": "species_group",
        "icon": "🏡",
        "species": [
            "Passer domesticus",
            "Columba livia",
            "Streptopelia decaocto",
            "Pica pica",
            "Turdus merula",
            "Erithacus rubecula",
            "Parus major",
            "Cyanistes caeruleus",
            "Fringilla coelebs",
            "Carduelis carduelis",
            "Sturnus vulgaris",
            "Motacilla alba",
        ],
    },
}


def get_poster_list():
  """Return list of all posters with basic info."""
  return [
      {
          "id": poster_id,
          "name": poster["name"],
          "icon": poster.get("icon", "🐦"),
      }
      for poster_id, poster in POSTERS.items()
  ]


def get_poster(poster_id: str):
  """Get a specific poster by ID."""
  return POSTERS.get(poster_id)


# Legacy compatibility
def get_region_list():
  """Legacy: return list of posters."""
  return get_poster_list()


def get_region(region_id: str):
  """Legacy: get a poster by ID, adapting keys for compatibility."""
  poster = POSTERS.get(region_id)
  if poster:
    return {
        "name": poster["name"],
        "common_birds": poster["species"],
        "type": poster.get("type", "regional"),
    }
  return None
