"""Predefined region configurations for regional bird posters."""

REGIONS = {
    "california": {
        "name": "California",
        "bounds": {
            "lat_min": 32.5,
            "lat_max": 42.0,
            "lon_min": -124.4,
            "lon_max": -114.1,
        },
        "common_birds": [
            "American Robin",
            "House Finch",
            "Anna's Hummingbird",
            "California Quail",
            "American Crow",
            "Northern Mockingbird",
            "Mourning Dove",
            "Red-tailed Hawk",
            "House Sparrow",
            "European Starling",
            "Western Scrub-Jay",
            "Black Phoebe",
            "Yellow-rumped Warbler",
            "White-crowned Sparrow",
            "Bushtit",
            "Dark-eyed Junco",
            "Lesser Goldfinch",
            "American Goldfinch",
            "Red-winged Blackbird",
            "Brewer's Blackbird",
            "California Towhee",
            "Spotted Towhee",
            "Song Sparrow",
            "Acorn Woodpecker",
            "Nuttall's Woodpecker",
            "Cooper's Hawk",
            "Turkey Vulture",
            "Great Blue Heron",
            "Mallard",
            "Canada Goose",
        ],
    },
    "western_us": {
        "name": "Western United States",
        "bounds": {
            "lat_min": 31.0,
            "lat_max": 49.0,
            "lon_min": -125.0,
            "lon_max": -102.0,
        },
        "common_birds": [
            "American Robin",
            "House Finch",
            "Anna's Hummingbird",
            "Black-capped Chickadee",
            "American Crow",
            "Northern Mockingbird",
            "Mourning Dove",
            "Red-tailed Hawk",
            "House Sparrow",
            "European Starling",
            "Steller's Jay",
            "Black Phoebe",
            "Yellow-rumped Warbler",
            "White-crowned Sparrow",
            "Dark-eyed Junco",
            "Lesser Goldfinch",
            "American Goldfinch",
            "Red-winged Blackbird",
            "Song Sparrow",
            "Downy Woodpecker",
            "Hairy Woodpecker",
            "Cooper's Hawk",
            "Turkey Vulture",
            "Great Blue Heron",
            "Mallard",
            "Canada Goose",
            "Bald Eagle",
            "Western Meadowlark",
            "Mountain Chickadee",
            "Rufous Hummingbird",
        ],
    },
    "uk": {
        "name": "United Kingdom",
        "bounds": {
            "lat_min": 49.9,
            "lat_max": 60.9,
            "lon_min": -8.6,
            "lon_max": 1.8,
        },
        "common_birds": [
            "European Robin",
            "House Sparrow",
            "Blue Tit",
            "Great Tit",
            "Blackbird",
            "Chaffinch",
            "Woodpigeon",
            "Magpie",
            "Carrion Crow",
            "Goldfinch",
            "Long-tailed Tit",
            "Wren",
            "Dunnock",
            "Coal Tit",
            "Greenfinch",
            "Great Spotted Woodpecker",
            "Nuthatch",
            "Jay",
            "Collared Dove",
            "Starling",
            "Song Thrush",
            "Mistle Thrush",
            "Pheasant",
            "Red Kite",
            "Buzzard",
            "Kestrel",
            "Grey Heron",
            "Mallard",
            "Mute Swan",
            "Canada Goose",
        ],
    },
    "france": {
        "name": "France",
        "bounds": {
            "lat_min": 41.3,
            "lat_max": 51.1,
            "lon_min": -5.1,
            "lon_max": 9.6,
        },
        "common_birds": [
            "European Robin",
            "House Sparrow",
            "Blue Tit",
            "Great Tit",
            "Blackbird",
            "Chaffinch",
            "Woodpigeon",
            "Magpie",
            "Carrion Crow",
            "Goldfinch",
            "Long-tailed Tit",
            "Wren",
            "Serin",
            "Greenfinch",
            "Great Spotted Woodpecker",
            "Nuthatch",
            "Jay",
            "Collared Dove",
            "Starling",
            "Song Thrush",
            "Hoopoe",
            "Bee-eater",
            "Red Kite",
            "Buzzard",
            "Kestrel",
            "Grey Heron",
            "Mallard",
            "Mute Swan",
            "Great Egret",
            "Black-headed Gull",
        ],
    },
}


def get_region_list():
    """Return list of available regions with basic info."""
    return [
        {"id": region_id, "name": region["name"]}
        for region_id, region in REGIONS.items()
    ]


def get_region(region_id: str):
    """Get a specific region by ID."""
    return REGIONS.get(region_id)
