# Generated by Django 4.2.2 on 2023-07-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("observation", "0009_alter_species_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("answers", models.JSONField(default=list)),
                ("correct_answer", models.IntegerField()),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="observation.species",
                    ),
                ),
            ],
        ),
    ]
