# Generated by Django 4.2.2 on 2023-07-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_quiz_options_quiz_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
