# Generated by Django 4.2.2 on 2023-09-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_quiz_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='answers',
            new_name='choices',
        ),
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='correct_answer',
            new_name='correct_choice',
        ),
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='prompt',
            new_name='question',
        ),
    ]
