# Generated by Django 4.2.2 on 2023-09-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_rename_answers_multiplechoicequestion_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='xp',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
