name: Deploy backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: upload source code of django app
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "backend/nature_go/*"
          target: "/srv/nature-go/nature_go"
          strip_components: 2
          rm: true

      - name: deploy new source on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key:  ${{ secrets.SSH_KEY }}
          passphrase:  ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            cd /srv/nature-go/
            python3 -m venv venv
            source venv/bin/activate
            cd /srv/nature-go/nature_go/
            pip install -r requirements.txt
            export SECRET_KEY=${{ secrets.SECRET_KEY }}
            python manage.py migrate --settings=nature_go.settings.production
            python manage.py collectstatic --no-input --settings=nature_go.settings.production
            sudo systemctl restart gunicorn
            sudo systemctl reload apache2
